/**
 * 把 src/styles/index.css 的 @import 展开成单个 static/style.css。
 *
 * 为什么不交给 Vite：当前 vite.config.js 用的是 build.lib + IIFE 模式，
 * 一旦从 JS 里 import CSS，Vite 会在 outDir 生成一个名为 style.css 的产物，
 * 正好**覆盖**线上服役中的 static/style.css。在还没切到 ESM 之前，
 * 这个脚本是风险最低的做法：零依赖、输出可预测、diff 可读。
 *
 * 批次 3 切到 ESM + 代码分割后，CSS 会改由 Vite 处理，本脚本随之删除。
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ENTRY = resolve(here, '../src/styles/index.css');
const OUT = resolve(here, '../../static/style.css');

/** 支持 `@import "x.css";` 与 `@import "x.css" layer(name);` 两种形式。 */
const IMPORT_RE = /^@import\s+(?:url\()?["']([^"']+)["']\)?(?:\s+layer\(([\w-]+)\))?\s*;?\s*$/;

/** @type {Set<string>} */
const seen = new Set();

/**
 * @param {string} file
 * @returns {Promise<string>}
 */
async function inline(file) {
  if (seen.has(file)) {
    throw new Error(`CSS 循环引用：${relative(here, file)}`);
  }
  seen.add(file);

  const source = await readFile(file, 'utf8');
  const output = [];

  for (const line of source.split('\n')) {
    const match = line.trim().match(IMPORT_RE);
    if (!match) { output.push(line); continue; }
    const target = resolve(dirname(file), match[1]);
    const layer = match[2];
    output.push(`/* ─── ${relative(resolve(here, '..'), target)}${layer ? ` → @layer ${layer}` : ''} ─── */`);
    const body = await inline(target);
    // layer() 形式：把整份文件包进级联层。用于把旧 style.css 整体降级，
    // 不必给它的 559 条选择器逐条加前缀。
    output.push(layer ? `@layer ${layer} {\n${body}\n}` : body);
  }

  seen.delete(file);
  return output.join('\n');
}

const banner = `/* BidProof workbench styles — generated by scripts/build-css.mjs.
   请勿直接编辑本文件；源文件在 frontend/src/styles/。 */\n`;

const css = banner + (await inline(ENTRY));
await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, css, 'utf8');

const kb = (Buffer.byteLength(css, 'utf8') / 1024).toFixed(1);
console.log(`build:css → static/style.css (${kb} kB)`);
