"""identity audit envelope

Revision ID: 2dbb331b707a
Revises: 50edb6898ab9
Create Date: 2026-09-02 14:12:34.177723
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2dbb331b707a'
down_revision: Union[str, None] = '50edb6898ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('token_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('permissions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('token_prefix', sa.Text(), server_default='', nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_api_tokens_workspace', ['workspace_id'], unique=False)

    op.create_table('identity_bindings',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('provider', 'issuer', 'subject', name='uq_identity_binding_subject')
    )
    with op.batch_alter_table('identity_bindings', schema=None) as batch_op:
        batch_op.create_index('idx_identity_bindings_user', ['user_id'], unique=False)

    op.create_table('login_flows',
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('nonce', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('consumed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('rate_limit_hits',
    sa.Column('hit_id', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('hit_id')
    )
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.create_index('idx_rate_limit_scope_bucket', ['scope', 'bucket', 'occurred_at'], unique=False)

    op.create_table('user_mfa',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.Text(), nullable=True),
    sa.Column('last_counter', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recovery_codes_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_ip', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.Text(), server_default='SUCCESS', nullable=False))
        batch_op.create_index('idx_audit_request', ['request_id'], unique=False)
        batch_op.create_index('idx_audit_type_created', ['event_type', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_type_created')
        batch_op.drop_index('idx_audit_request')
        batch_op.drop_column('outcome')
        batch_op.drop_column('request_id')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('actor_ip')

    op.drop_table('user_mfa')
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.drop_index('idx_rate_limit_scope_bucket')

    op.drop_table('rate_limit_hits')
    op.drop_table('login_flows')
    with op.batch_alter_table('identity_bindings', schema=None) as batch_op:
        batch_op.drop_index('idx_identity_bindings_user')

    op.drop_table('identity_bindings')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_api_tokens_workspace')

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
