"""Baseline schema matching app.models at the time Alembic was introduced.

Generated by autogenerate from app.models.metadata. Pilot databases created before this
revision are brought forward by stamping this revision, since their tables already exist.

Revision ID: 50edb6898ab9
Revises: 
Create Date: 2026-09-02 13:42:18.210819
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '50edb6898ab9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('accuracy_feedback',
    sa.Column('feedback_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('requirement_id', sa.Text(), nullable=True),
    sa.Column('feedback_key', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('predicted', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('locator_label', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.Text(), nullable=False),
    sa.Column('dataset_scope', sa.Text(), server_default='TEST', nullable=False),
    sa.Column('review_complete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('accuracy_feedback', schema=None) as batch_op:
        batch_op.create_index('idx_accuracy_feedback_key', ['workspace_id', 'run_id', 'reviewer_id', 'feedback_key'], unique=True)
        batch_op.create_index('idx_accuracy_feedback_scope', ['workspace_id', 'dataset_scope'], unique=False)

    op.create_table('audit_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_audit_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_workspace_run', ['workspace_id', 'run_id'], unique=False)

    op.create_table('auth_action_tokens',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('used_at', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('auth_action_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_auth_action_tokens_invite', ['purpose', 'username'], unique=False)
        batch_op.create_index('idx_auth_action_tokens_reset', ['purpose', 'user_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_auth_sessions_user', ['user_id'], unique=False)

    op.create_table('comments',
    sa.Column('comment_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_workspace_run', ['workspace_id', 'run_id'], unique=False)

    op.create_table('projects',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_projects_workspace_code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_workspace', ['workspace_id'], unique=False)

    op.create_table('remediations',
    sa.Column('remediation_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('requirement_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='OPEN', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('remediation_id')
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index('idx_remediations_workspace_due', ['workspace_id', 'due_date'], unique=False)
        batch_op.create_index('idx_remediations_workspace_run', ['workspace_id', 'run_id'], unique=False)

    op.create_table('runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Text(), server_default='local', nullable=False),
    sa.Column('owner_id', sa.Text(), server_default='local-owner', nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('favorite', sa.Integer(), server_default='0', nullable=False),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('tender_sha256', sa.Text(), nullable=True),
    sa.Column('duplicate_run_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('tender_filename', sa.Text(), nullable=False),
    sa.Column('tender_path', sa.Text(), nullable=False),
    sa.Column('evidence_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requirements_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_documents_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('evidence_assets_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('decision_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('idx_runs_project', ['project_id'], unique=False)
        batch_op.create_index('idx_runs_workspace_archived', ['workspace_id', 'archived_at'], unique=False)
        batch_op.create_index('idx_runs_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('idx_runs_workspace_sha', ['workspace_id', 'tender_sha256'], unique=False)
        batch_op.create_index('idx_runs_workspace_updated', ['workspace_id', 'updated_at'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_message', sa.Text(), server_default='', nullable=False),
    sa.Column('cancel_requested', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_scan_jobs_run', ['run_id'], unique=False)
        batch_op.create_index('idx_scan_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_scan_jobs_workspace_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_workspace', ['workspace_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('retention_days', sa.Integer(), server_default='365', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index('idx_workspaces_created_at', ['created_at'], unique=False)



def downgrade() -> None:
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('idx_workspaces_created_at')

    op.drop_table('workspaces')
    op.drop_table('workspace_members')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_workspace')

    op.drop_table('users')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_jobs_workspace_created')
        batch_op.drop_index('idx_scan_jobs_status_created')
        batch_op.drop_index('idx_scan_jobs_run')

    op.drop_table('scan_jobs')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('idx_runs_workspace_updated')
        batch_op.drop_index('idx_runs_workspace_sha')
        batch_op.drop_index('idx_runs_workspace_created')
        batch_op.drop_index('idx_runs_workspace_archived')
        batch_op.drop_index('idx_runs_project')

    op.drop_table('runs')
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index('idx_remediations_workspace_run')
        batch_op.drop_index('idx_remediations_workspace_due')

    op.drop_table('remediations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_workspace')

    op.drop_table('projects')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_workspace_run')

    op.drop_table('comments')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_auth_sessions_user')

    op.drop_table('auth_sessions')
    with op.batch_alter_table('auth_action_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_auth_action_tokens_reset')
        batch_op.drop_index('idx_auth_action_tokens_invite')

    op.drop_table('auth_action_tokens')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_workspace_run')
        batch_op.drop_index('idx_audit_workspace_created')

    op.drop_table('audit_events')
    with op.batch_alter_table('accuracy_feedback', schema=None) as batch_op:
        batch_op.drop_index('idx_accuracy_feedback_scope')
        batch_op.drop_index('idx_accuracy_feedback_key')

    op.drop_table('accuracy_feedback')
