import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  CalendarClock,
  ChartNoAxesCombined,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  CircleStop,
  ClipboardCheck,
  ClipboardPlus,
  CopyCheck,
  createElement,
  DatabaseBackup,
  DatabaseZap,
  Download,
  Eye,
  EyeOff,
  FileArchive,
  FileCheck2,
  FileDown,
  FilePlus2,
  FileSearch,
  FileText,
  Files,
  FilterX,
  Folder,
  FolderKanban,
  FolderPlus,
  GitCompareArrows,
  Inbox,
  Key,
  KeyRound,
  ListChecks,
  ListRestart,
  LoaderCircle,
  LogIn,
  LogOut,
  MessageCircleWarning,
  MessageSquarePlus,
  Minus,
  MonitorSmartphone,
  Moon,
  Plus,
  RefreshCcw,
  RefreshCw,
  Save,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Table2,
  Trash2,
  TriangleAlert,
  UploadCloud,
  UserCog,
  UserRound,
  UsersRound,
  X,
} from 'lucide';

const REGISTRY = {
  activity: Activity,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'calendar-clock': CalendarClock,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  'circle-stop': CircleStop,
  'clipboard-check': ClipboardCheck,
  'clipboard-plus': ClipboardPlus,
  'copy-check': CopyCheck,
  'database-backup': DatabaseBackup,
  'database-zap': DatabaseZap,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-archive': FileArchive,
  'file-check-2': FileCheck2,
  'file-down': FileDown,
  'file-plus-2': FilePlus2,
  'file-search': FileSearch,
  'file-text': FileText,
  files: Files,
  'filter-x': FilterX,
  folder: Folder,
  'folder-kanban': FolderKanban,
  'folder-plus': FolderPlus,
  'git-compare-arrows': GitCompareArrows,
  inbox: Inbox,
  key: Key,
  'key-round': KeyRound,
  'list-checks': ListChecks,
  'list-restart': ListRestart,
  'loader-circle': LoaderCircle,
  'log-in': LogIn,
  'log-out': LogOut,
  'message-circle-warning': MessageCircleWarning,
  'message-square-plus': MessageSquarePlus,
  minus: Minus,
  'monitor-smartphone': MonitorSmartphone,
  moon: Moon,
  plus: Plus,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  save: Save,
  'scan-line': ScanLine,
  'scan-search': ScanSearch,
  search: Search,
  send: Send,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  'table-2': Table2,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'upload-cloud': UploadCloud,
  'user-cog': UserCog,
  'user-round': UserRound,
  'users-round': UsersRound,
  x: X,
};

export function refreshIcons(root = document) {
  root.querySelectorAll('i[data-lucide]').forEach((node) => {
    const icon = REGISTRY[node.dataset.lucide];
    if (!icon) return;
    const svg = createElement(icon, { 'aria-hidden': 'true' });
    if (node.className) svg.setAttribute('class', node.className);
    node.replaceWith(svg);
  });
}
